// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQh1DFkhPQmxrBt6TvD2ooNUsEfTGC1CA',
    appId: '1:645189966226:web:5ee540d825d1f2d1e4c94b',
    messagingSenderId: '645189966226',
    projectId: 'ascent-21a21',
    authDomain: 'ascent-21a21.firebaseapp.com',
    storageBucket: 'ascent-21a21.appspot.com',
    measurementId: 'G-P7E7D71P6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnHpj8EeQetCDRz4FrOiMQhssyK_zV3Q',
    appId: '1:645189966226:android:14216fe2eb08ec3be4c94b',
    messagingSenderId: '645189966226',
    projectId: 'ascent-21a21',
    storageBucket: 'ascent-21a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIyubDJXdvuYJRm_CEI_RqjBaK4B3h9hg',
    appId: '1:645189966226:ios:19b988d1413cb892e4c94b',
    messagingSenderId: '645189966226',
    projectId: 'ascent-21a21',
    storageBucket: 'ascent-21a21.appspot.com',
    iosBundleId: 'com.gofin.ascent',
  );
}
