// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATElHOJnvZTkE0Jp3praLOCJfjDqsaeMw',
    appId: '1:546565231416:web:61c35fe3fdcd260b9d67cd',
    messagingSenderId: '546565231416',
    projectId: 'co-escape-app',
    authDomain: 'co-escape-app.firebaseapp.com',
    storageBucket: 'co-escape-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChmiDYjCrV6_Y_utevrVzJ-NmBYXnVO9Q',
    appId: '1:546565231416:android:47a2ce5db8ae678c9d67cd',
    messagingSenderId: '546565231416',
    projectId: 'co-escape-app',
    storageBucket: 'co-escape-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA85mWlercvfoRbTUufajc4eeLhHfFOxE',
    appId: '1:546565231416:ios:f9dcdd5b629d96199d67cd',
    messagingSenderId: '546565231416',
    projectId: 'co-escape-app',
    storageBucket: 'co-escape-app.appspot.com',
    iosBundleId: 'com.gofin.coescape',
  );
}
